package ttl.jaxwsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HelloJaxwsService service = new HelloJaxwsService();
 * HelloJaxwsDelegate portType = service.getHelloJaxwsPort();
 * portType.add(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HelloJaxwsService", targetNamespace = "http://jaxws.ttl/", wsdlLocation = "http://localhost:8080/javajaxwsHello/HelloJaxwsPort?wsdl")
public class HelloJaxwsService extends Service {

	private final static URL HELLOJAXWSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(ttl.jaxwsclient.HelloJaxwsService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = ttl.jaxwsclient.HelloJaxwsService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/javajaxwsHello/HelloJaxwsPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/javajaxwsHello/HelloJaxwsPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HELLOJAXWSSERVICE_WSDL_LOCATION = url;
	}

	public HelloJaxwsService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HelloJaxwsService() {
		super(HELLOJAXWSSERVICE_WSDL_LOCATION, new QName("http://jaxws.ttl/",
				"HelloJaxwsService"));
	}

	/**
	 * 
	 * @return returns HelloJaxwsDelegate
	 */
	@WebEndpoint(name = "HelloJaxwsPort")
	public HelloJaxwsDelegate getHelloJaxwsPort() {
		return super.getPort(new QName("http://jaxws.ttl/", "HelloJaxwsPort"),
				HelloJaxwsDelegate.class);
	}

}
