package ttl.jaxwsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloJaxwsDelegate", targetNamespace = "http://jaxws.ttl/")
public interface HelloJaxwsDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "add", targetNamespace = "http://jaxws.ttl/", className = "ttl.jaxwsclient.Add")
	@ResponseWrapper(localName = "addResponse", targetNamespace = "http://jaxws.ttl/", className = "ttl.jaxwsclient.AddResponse")
	public int add(@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://jaxws.ttl/", className = "ttl.jaxwsclient.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jaxws.ttl/", className = "ttl.jaxwsclient.SayHelloResponse")
	public String sayHello(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
